// GENERATED by scripts/gen-ksa-entries.mjs from knowledge/ksa/*.md — DO NOT EDIT BY HAND.
// Regenerate after any pack frontmatter change (e.g. the curation inject_summary PR):
//   node scripts/gen-ksa-entries.mjs
// The selector test (scripts/proof-ksa-encyclopedia.test.ts) re-parses the pack and
// asserts this stays in sync, so drift fails CI.

export interface KsaEntry {
  id: string;
  nameAr: string;
  nameEn: string;
  category: string;
  cuisineTags: string[];
  regions: string[];
  menuJoinHint: string;
  /** ≤160-char curated culture line; NULL until the curation pack-PR lands. */
  injectSummary: string | null;
}

export const KSA_ENTRIES: readonly KsaEntry[] = [
  {
    "id": "arabic-tea",
    "nameAr": "شاي / شاهي (أحمر، بالنعناع، بالزعفران)",
    "nameEn": "Arabic Tea (Shai)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "hospitality",
      "hot-drink",
      "tea",
      "ramadan",
      "gahwa-pairing"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "eastern",
      "all"
    ],
    "menuJoinHint": "Red tea (often with mint or saffron), served sweet. Offer only if the tenant sells tea. Match the real variants the item lists (mint/na'na, saffron, plain).",
    "injectSummary": "شاهي أحمر دافئ ومحلّى، بالنعناع المنعش أو الزعفران الذهبي؛ رفيق الجلسة بعد القهوة وطبق الحلا."
  },
  {
    "id": "aseedah",
    "nameAr": "عصيدة",
    "nameEn": "Aseedah",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "comfort",
      "heritage",
      "dough",
      "sweet-or-savoury",
      "winter",
      "ramadan"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "all"
    ],
    "menuJoinHint": "Aseedah is a thick cooked-flour dough, served sweet (with honey/dibs/ghee) or plain. Offer only if the tenant sells it. Clarify sweet vs savoury per the tenant item.",
    "injectSummary": "عجينة دقيق سميكة مطاطية؛ الحلوة غنية بالعسل والسمن، والسادة هادئة ومشبعة — دفء بيتي على السفرة."
  },
  {
    "id": "dates",
    "nameAr": "تمر / رطب / تمور",
    "nameEn": "Dates (Tamr)",
    "category": "staple",
    "cuisineTags": [
      "saudi",
      "hospitality",
      "hot-drink-pairing",
      "ramadan",
      "sweet",
      "al-ahsa",
      "gahwa"
    ],
    "regions": [
      "eastern",
      "najd",
      "all"
    ],
    "menuJoinHint": "Dates are the universal companion to gahwa. Offer only if the tenant sells dates (as an item or a side). Named varieties (Ajwa, Sukkari, Khalas...) only if the tenant lists them.",
    "injectSummary": "حلاوة الترحاب ورفيقة القهوة؛ من السكري المقرمش إلى الخلاص الطري والعجوة الداكنة — بها يُفتتح المجلس."
  },
  {
    "id": "gahwa",
    "nameAr": "القهوة العربية / القهوة السعودية / قهوة عربي",
    "nameEn": "Arabic Coffee (Gahwa)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "najdi",
      "hijazi",
      "hospitality",
      "hot-drink",
      "coffee",
      "gahwa"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "eastern",
      "all"
    ],
    "menuJoinHint": "Recommend only if the tenant sells Arabic coffee / قهوة عربية (or a close menu item). Never invent it. If the tenant has dates/تمر AND gahwa on the menu, the gahwa-with-dates pairing is the natural offer; if either is missing, do not imply it exists.",
    "injectSummary": "روح الكرم السعودي؛ قهوة فاتحة بالهيل والزعفران تُقدَّم مع التمر في فنجان صغير — أول ما يستقبل به الضيف."
  },
  {
    "id": "harees",
    "nameAr": "هريس / هريسة",
    "nameEn": "Harees (Hareesa)",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "eastern",
      "grain",
      "comfort",
      "ramadan",
      "wheat"
    ],
    "regions": [
      "hijaz",
      "eastern",
      "all"
    ],
    "menuJoinHint": "Harees is a smooth wheat-and-meat porridge, big in Ramadan. Offer only if the tenant sells it. Smoother than jareesh; do not conflate.",
    "injectSummary": "هريس ناعم حريري من القمح واللحم، غني القوام بلا قشطة؛ خفيف على النفس ومشبع — من كلاسيكيات مائدة الإفطار."
  },
  {
    "id": "jareesh",
    "nameAr": "جريش",
    "nameEn": "Jareesh",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "grain",
      "comfort",
      "heritage",
      "wheat"
    ],
    "regions": [
      "najd"
    ],
    "menuJoinHint": "Jareesh is a Najdi crushed-wheat dish. Offer only if the tenant sells it. Distinct from margoog (dough) and harees (whole wheat, smoother).",
    "injectSummary": "قمح مجروش يُطبخ حتى يصير كريمياً؛ قوامه خشن لذيذ وطعمه حامض-كريمي مع اللبن، أكلة نجدية بيتية مشبعة."
  },
  {
    "id": "kabsa",
    "nameAr": "كبسة",
    "nameEn": "Kabsa",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "rice-dish",
      "main-course",
      "meat",
      "hospitality",
      "signature"
    ],
    "regions": [
      "najd",
      "eastern",
      "all"
    ],
    "menuJoinHint": "Kabsa is the KSA national centrepiece — most Saudi restaurants sell a version (kabsa dajaj/laham/robyan). Map the customer's craving to the tenant's real kabsa item(s) and their real variants (chicken/lamb/shrimp, portion sizes). Never invent a protein or size the item doesn't list.",
    "injectSummary": "نجمة المائدة السعودية؛ رز عطري بمرق غني ولمسة لومي حامضة، دجاج أو لحم أو روبيان — طبق الاجتماع والضيافة."
  },
  {
    "id": "laban",
    "nameAr": "لبن (لبن رايب / متبّل)",
    "nameEn": "Laban (Cultured Buttermilk)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "cold-drink",
      "dairy",
      "meal-pairing",
      "everyday"
    ],
    "regions": [
      "najd",
      "eastern",
      "all"
    ],
    "menuJoinHint": "Laban is the classic savoury drink alongside rice/meat meals. Offer only if the tenant sells it (as a drink or side). Distinct from sweet flavoured milk; do not substitute.",
    "injectSummary": "لبن رايب بارد، حامض خفيف ومالح، يقطع دسم الرز والمشوي؛ المشروب المالح الكلاسيكي جنب الكبسة والمندي."
  },
  {
    "id": "mandi",
    "nameAr": "مندي",
    "nameEn": "Mandi",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "yemeni-origin",
      "rice-dish",
      "main-course",
      "meat",
      "signature"
    ],
    "regions": [
      "hijaz",
      "asir",
      "all"
    ],
    "menuJoinHint": "Mandi (chicken or lamb) is a menu staple, especially in Hijaz/Asir. Map to the tenant's real mandi item, its real protein choices and portion sizes. Do not conflate with kabsa or madfoon unless the menu lists them separately.",
    "injectSummary": "لحم أو دجاج يذوب من العظم ورز خفيف مدخّن بنكهة الشواء؛ ألطف وأكثر تدخيناً من الكبسة — نجم موائد الحجاز وعسير."
  },
  {
    "id": "margoog",
    "nameAr": "مرقوق",
    "nameEn": "Margoog (Marqooq)",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "stew",
      "comfort",
      "dough",
      "vegetables",
      "winter"
    ],
    "regions": [
      "najd",
      "all"
    ],
    "menuJoinHint": "Margoog is a Najdi dough-and-vegetable stew. Offer only if the tenant sells it. Related to jareesh/qursan/matazeez — keep them distinct per the menu.",
    "injectSummary": "عجين قمح طري بمرق الخضار واللحم الكثيف؛ أكلة نجدية دافئة ومشبعة، راحة الشتاء أكثر من كونها طبق استعراض."
  },
  {
    "id": "mathloutha",
    "nameAr": "مثلوثة",
    "nameEn": "Mathloutha",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "qassim",
      "grain",
      "comfort",
      "heritage",
      "winter"
    ],
    "regions": [
      "najd"
    ],
    "menuJoinHint": "Mathloutha is a Qassim/Najdi dish that combines three heritage dishes in one bowl (jareesh + margoog + qursan). Offer only if the tenant sells it. Niche — do not invent.",
    "injectSummary": "ثلاث أكلات نجدية في صحن واحد — جريش ومرقوق وقرصان؛ قمة الراحة القصيمية، خشنة وطرية ومشبعة معاً."
  },
  {
    "id": "mutabbaq",
    "nameAr": "مطبق",
    "nameEn": "Mutabbaq",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "street-food",
      "savoury",
      "snack",
      "ramadan",
      "pastry"
    ],
    "regions": [
      "hijaz"
    ],
    "menuJoinHint": "Mutabbaq is a Hijazi stuffed folded pastry (savoury meat/egg, or sweet banana). Offer only if the tenant sells it, and only the fillings the item lists.",
    "injectSummary": "معجنة حجازية ذهبية مقرمشة من الخارج؛ الحشو المالح متبّل بالبيض واللحم، والموز الحلو طري — لقمة يدوية من أكل الشارع."
  },
  {
    "id": "ramadan-drinks",
    "nameAr": "مشروبات رمضان (فيمتو، سوبيا، قمر الدين، تمر هندي، جلاب)",
    "nameEn": "Ramadan Drinks (Vimto, Sobia, Qamar al-Din, Tamarind, Jallab)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "cold-drink",
      "ramadan",
      "sweet",
      "iftar"
    ],
    "regions": [
      "hijaz",
      "najd",
      "all"
    ],
    "menuJoinHint": "A category of iftar drinks. Offer only the specific drinks the tenant actually sells (Vimto, sobia, qamar al-din, tamr hindi, jallab). Never present the whole category as available; never invent a flavour.",
    "injectSummary": "مشروبات الإفطار المنعشة: فيمتو التوت، السوبيا الكريمية، قمر الدين المشمشي، التمر هندي والجلاب — حلوة ومبرّدة."
  },
  {
    "id": "saleeg",
    "nameAr": "سليق",
    "nameEn": "Saleeg",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "taif",
      "rice-dish",
      "main-course",
      "comfort",
      "creamy"
    ],
    "regions": [
      "hijaz"
    ],
    "menuJoinHint": "Saleeg is a Hijazi/Taif specialty — creamy rice with chicken. Offer only if the tenant sells it. It is distinct from kabsa/mandi; do not substitute silently.",
    "injectSummary": "رز طائفي كريمي طري بالدجاج، هادئ ومريح، والشطة الجانبية تعطيه الحرارة — تخصص حجازي أصيل يختلف عن الكبسة والمندي."
  },
  {
    "id": "saudi-sweets",
    "nameAr": "حلويات سعودية (كليجا، معمول، دبيازة، لقيمات)",
    "nameEn": "Saudi Sweets (Kleija, Maamoul, Debyazah, Luqaimat)",
    "category": "sweet",
    "cuisineTags": [
      "saudi",
      "najdi",
      "hijazi",
      "sweet",
      "dessert",
      "eid",
      "ramadan",
      "gahwa-pairing"
    ],
    "regions": [
      "najd",
      "hijaz",
      "all"
    ],
    "menuJoinHint": "Covers several sweets (kleija, maamoul, debyazah, luqaimat). Offer only the specific sweets the tenant actually sells, by their real names. Do not present the whole category as available.",
    "injectSummary": "حلا سعودي دافئ التوابل: كليجا ومعمول بحشو التمر، دبيازة فاكهية، ولقيمات مقرمشة مغموسة بالقطر — كلها رفيقة القهوة."
  }
] as const;
