// GENERATED by scripts/gen-ksa-entries.mjs from knowledge/ksa/*.md — DO NOT EDIT BY HAND.
// Regenerate after any pack frontmatter change (e.g. the curation inject_summary PR):
//   node scripts/gen-ksa-entries.mjs
// The selector test (scripts/proof-ksa-encyclopedia.test.ts) re-parses the pack and
// asserts this stays in sync, so drift fails CI.

export interface KsaEntry {
  id: string;
  nameAr: string;
  nameEn: string;
  category: string;
  cuisineTags: string[];
  regions: string[];
  menuJoinHint: string;
  /** ≤160-char curated culture line; NULL until the curation pack-PR lands. */
  injectSummary: string | null;
}

export const KSA_ENTRIES: readonly KsaEntry[] = [
  {
    "id": "arabic-tea",
    "nameAr": "شاي / شاهي (أحمر، بالنعناع، بالزعفران)",
    "nameEn": "Arabic Tea (Shai)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "hospitality",
      "hot-drink",
      "tea",
      "ramadan",
      "gahwa-pairing"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "eastern",
      "all"
    ],
    "menuJoinHint": "شاي أحمر. اعرضه فقط لو المطعم يبيعه، وطابِق نكهاته (نعناع/زعفران/سادة) بالمنيو.",
    "injectSummary": "شاهي أحمر دافئ ومحلّى، بالنعناع المنعش أو الزعفران الذهبي؛ رفيق الجلسة بعد القهوة وطبق الحلا."
  },
  {
    "id": "aseedah",
    "nameAr": "عصيدة",
    "nameEn": "Aseedah",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "comfort",
      "heritage",
      "dough",
      "sweet-or-savoury",
      "winter",
      "ramadan"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "all"
    ],
    "menuJoinHint": "عجينة دقيق مطبوخة، حلوة (عسل/دبس/سمن) أو سادة. اعرضها فقط لو المطعم يبيعها، ووضّح الحلو من السادة حسب الصنف.",
    "injectSummary": "عجينة دقيق سميكة مطاطية؛ الحلوة غنية بالعسل والسمن، والسادة هادئة ومشبعة — دفء بيتي على السفرة."
  },
  {
    "id": "dates",
    "nameAr": "تمر / رطب / تمور",
    "nameEn": "Dates (Tamr)",
    "category": "staple",
    "cuisineTags": [
      "saudi",
      "hospitality",
      "hot-drink-pairing",
      "ramadan",
      "sweet",
      "al-ahsa",
      "gahwa"
    ],
    "regions": [
      "eastern",
      "najd",
      "all"
    ],
    "menuJoinHint": "التمر رفيق القهوة. اعرضه فقط لو المطعم يبيعه، والأنواع المسمّاة فقط لو مذكورة بالمنيو.",
    "injectSummary": "حلاوة الترحاب ورفيقة القهوة؛ من السكري المقرمش إلى الخلاص الطري والعجوة الداكنة — بها يُفتتح المجلس."
  },
  {
    "id": "gahwa",
    "nameAr": "القهوة العربية / القهوة السعودية / قهوة عربي",
    "nameEn": "Arabic Coffee (Gahwa)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "najdi",
      "hijazi",
      "hospitality",
      "hot-drink",
      "coffee",
      "gahwa"
    ],
    "regions": [
      "najd",
      "hijaz",
      "asir",
      "eastern",
      "all"
    ],
    "menuJoinHint": "اعرضها فقط لو المطعم يبيع قهوة عربية، ولا تخترعها.",
    "injectSummary": "روح الكرم السعودي؛ قهوة فاتحة بالهيل والزعفران تُقدَّم مع التمر في فنجان صغير — أول ما يستقبل به الضيف."
  },
  {
    "id": "harees",
    "nameAr": "هريس / هريسة",
    "nameEn": "Harees (Hareesa)",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "eastern",
      "grain",
      "comfort",
      "ramadan",
      "wheat"
    ],
    "regions": [
      "hijaz",
      "eastern",
      "all"
    ],
    "menuJoinHint": "هريس قمح ولحم ناعم، كثير برمضان. اعرضه فقط لو المطعم يبيعه، وهو أنعم من الجريش فلا تخلط بينهما.",
    "injectSummary": "هريس ناعم حريري من القمح واللحم، غني القوام بلا قشطة؛ خفيف على النفس ومشبع — من كلاسيكيات مائدة الإفطار."
  },
  {
    "id": "jareesh",
    "nameAr": "جريش",
    "nameEn": "Jareesh",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "grain",
      "comfort",
      "heritage",
      "wheat"
    ],
    "regions": [
      "najd"
    ],
    "menuJoinHint": "أكلة قمح مجروش نجدية. اعرضها فقط لو المطعم يبيعها، وميّزها عن المرقوق (عجين) والهريس (أنعم).",
    "injectSummary": "قمح مجروش يُطبخ حتى يصير كريمياً؛ قوامه خشن لذيذ وطعمه حامض-كريمي مع اللبن، أكلة نجدية بيتية مشبعة."
  },
  {
    "id": "kabsa",
    "nameAr": "كبسة",
    "nameEn": "Kabsa",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "rice-dish",
      "main-course",
      "meat",
      "hospitality",
      "signature"
    ],
    "regions": [
      "najd",
      "eastern",
      "all"
    ],
    "menuJoinHint": "طابِق رغبة العميل مع كبسة المطعم وأنواعها (دجاج/لحم/روبيان). لا تخترع بروتيناً أو حجماً.",
    "injectSummary": "نجمة المائدة السعودية؛ رز عطري بمرق غني ولمسة لومي حامضة، دجاج أو لحم أو روبيان — طبق الاجتماع والضيافة."
  },
  {
    "id": "laban",
    "nameAr": "لبن (لبن رايب / متبّل)",
    "nameEn": "Laban (Cultured Buttermilk)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "cold-drink",
      "dairy",
      "meal-pairing",
      "everyday"
    ],
    "regions": [
      "najd",
      "eastern",
      "all"
    ],
    "menuJoinHint": "مشروب مالح جنب الرز واللحم. اعرضه فقط لو المطعم يبيعه، ولا تبدّله بالحليب الحلو.",
    "injectSummary": "لبن رايب بارد، حامض خفيف ومالح، يقطع دسم الرز والمشوي؛ المشروب المالح الكلاسيكي جنب الكبسة والمندي."
  },
  {
    "id": "mandi",
    "nameAr": "مندي",
    "nameEn": "Mandi",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "yemeni-origin",
      "rice-dish",
      "main-course",
      "meat",
      "signature"
    ],
    "regions": [
      "hijaz",
      "asir",
      "all"
    ],
    "menuJoinHint": "طابِق مع مندي المطعم الحقيقي وبروتيناته وأحجامه. لا تخلطه بالكبسة أو المدفون.",
    "injectSummary": "لحم أو دجاج يذوب من العظم ورز خفيف مدخّن بنكهة الشواء؛ ألطف وأكثر تدخيناً من الكبسة — نجم موائد الحجاز وعسير."
  },
  {
    "id": "margoog",
    "nameAr": "مرقوق",
    "nameEn": "Margoog (Marqooq)",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "stew",
      "comfort",
      "dough",
      "vegetables",
      "winter"
    ],
    "regions": [
      "najd",
      "all"
    ],
    "menuJoinHint": "يخنة عجين وخضار نجدية. اعرضها فقط لو المطعم يبيعها، وميّزها عن الجريش والقرصان والمطازيز.",
    "injectSummary": "عجين قمح طري بمرق الخضار واللحم الكثيف؛ أكلة نجدية دافئة ومشبعة، راحة الشتاء أكثر من كونها طبق استعراض."
  },
  {
    "id": "mathloutha",
    "nameAr": "مثلوثة",
    "nameEn": "Mathloutha",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "najdi",
      "qassim",
      "grain",
      "comfort",
      "heritage",
      "winter"
    ],
    "regions": [
      "najd"
    ],
    "menuJoinHint": "طبق قصيمي يجمع جريش ومرقوق وقرصان. اعرضه فقط لو المطعم يبيعه. نادر — لا تخترعه.",
    "injectSummary": "ثلاث أكلات نجدية في صحن واحد — جريش ومرقوق وقرصان؛ قمة الراحة القصيمية، خشنة وطرية ومشبعة معاً."
  },
  {
    "id": "mutabbaq",
    "nameAr": "مطبق",
    "nameEn": "Mutabbaq",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "street-food",
      "savoury",
      "snack",
      "ramadan",
      "pastry"
    ],
    "regions": [
      "hijaz"
    ],
    "menuJoinHint": "معجنة حجازية محشوة (لحم/بيض أو موز). اعرضها فقط لو المطعم يبيعها، وبالحشوات المذكورة بالصنف فقط.",
    "injectSummary": "معجنة حجازية ذهبية مقرمشة من الخارج؛ الحشو المالح متبّل بالبيض واللحم، والموز الحلو طري — لقمة يدوية من أكل الشارع."
  },
  {
    "id": "ramadan-drinks",
    "nameAr": "مشروبات رمضان (فيمتو، سوبيا، قمر الدين، تمر هندي، جلاب)",
    "nameEn": "Ramadan Drinks (Vimto, Sobia, Qamar al-Din, Tamarind, Jallab)",
    "category": "beverage",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "cold-drink",
      "ramadan",
      "sweet",
      "iftar"
    ],
    "regions": [
      "hijaz",
      "najd",
      "all"
    ],
    "menuJoinHint": "قدّم المتوفر فقط.",
    "injectSummary": "مشروبات الإفطار المنعشة: فيمتو التوت، السوبيا الكريمية، قمر الدين المشمشي، التمر هندي والجلاب — حلوة ومبرّدة."
  },
  {
    "id": "saleeg",
    "nameAr": "سليق",
    "nameEn": "Saleeg",
    "category": "dish",
    "cuisineTags": [
      "saudi",
      "hijazi",
      "taif",
      "rice-dish",
      "main-course",
      "comfort",
      "creamy"
    ],
    "regions": [
      "hijaz"
    ],
    "menuJoinHint": "تخصص حجازي طائفي: رز كريمي بالدجاج. اعرضه فقط لو المطعم يبيعه، ولا تبدّله صامتاً بالكبسة أو المندي.",
    "injectSummary": "رز طائفي كريمي طري بالدجاج، هادئ ومريح، والشطة الجانبية تعطيه الحرارة — تخصص حجازي أصيل يختلف عن الكبسة والمندي."
  },
  {
    "id": "saudi-sweets",
    "nameAr": "حلويات سعودية (كليجا، معمول، دبيازة، لقيمات)",
    "nameEn": "Saudi Sweets (Kleija, Maamoul, Debyazah, Luqaimat)",
    "category": "sweet",
    "cuisineTags": [
      "saudi",
      "najdi",
      "hijazi",
      "sweet",
      "dessert",
      "eid",
      "ramadan",
      "gahwa-pairing"
    ],
    "regions": [
      "najd",
      "hijaz",
      "all"
    ],
    "menuJoinHint": "اعرض ما يبيعه المطعم فقط.",
    "injectSummary": "حلا سعودي دافئ التوابل: كليجا ومعمول بحشو التمر، دبيازة فاكهية، ولقيمات مقرمشة مغموسة بالقطر — كلها رفيقة القهوة."
  }
] as const;
