-- 0113 — atomic per-tenant order numbers
-- APPLIED to production 2026-08-27 via Supabase apply_migration (version 20260827040047).
--
-- ⚠ SUPERSEDED IN PART BY 0114. The grant block at the bottom of this file is
-- NOT sufficient on Supabase: `revoke … from public` leaves the default
-- privileges that grant anon/authenticated EXECUTE directly. Between 0113 and
-- 0114 this function was callable with the public browser key. The SQL below is
-- left byte-faithful to what was applied; 0114 is the fix. Do not copy the
-- grant idiom from here.
--
-- Order numbers were generated by reading EVERY order row for the tenant, taking
-- the numeric max and adding one (lib/db/orders-create.ts nextOrderNumber).
--
-- Two defects:
--   1. RACE. Read-then-write with no lock. Two orders created in the same instant
--      both read the same max and both take the same number. There was also NO
--      unique constraint on (restaurant_id, order_number), so both persisted —
--      nothing in the database refused it. Two customers, one order number, and
--      the operator cannot tell them apart.
--   2. O(n). A full tenant scan on every order creation. Harmless at 141 orders,
--      a table scan per order at 50,000.
--
-- This makes the DATABASE the authority. A per-tenant counter row is incremented
-- inside a single INSERT … ON CONFLICT DO UPDATE, which takes a row lock, so two
-- concurrent callers serialise and get different numbers. Constant time.
--
-- Verified before applying: 141 orders, 0 null order_numbers, 0 without digits,
-- 0 duplicates — so the unique index below cannot fail on existing data.
-- Verified after applying: 5 successive calls returned 5 distinct sequential
-- numbers, and every seeded counter equalled that tenant's true max.

create table if not exists public.order_number_counters (
  restaurant_id uuid primary key references public.restaurants(id) on delete cascade,
  next_number   bigint      not null,
  updated_at    timestamptz not null default now()
);

alter table public.order_number_counters enable row level security;
-- No policy: this table is service-role only. The counter is never read from a
-- browser, and RLS-on-with-no-policy denies every anon/authenticated request.

-- Seed each existing tenant with its CURRENT max, not max+1: the function below
-- increments before returning, so the first call after seeding yields max+1 and
-- no number is skipped.
insert into public.order_number_counters (restaurant_id, next_number)
select o.restaurant_id,
       max((nullif(regexp_replace(o.order_number, '\D', '', 'g'), ''))::bigint)
from public.orders o
where o.order_number is not null
  and nullif(regexp_replace(o.order_number, '\D', '', 'g'), '') is not null
group by o.restaurant_id
on conflict (restaurant_id) do nothing;

-- Atomic allocation. ON CONFLICT DO UPDATE locks the counter row, so concurrent
-- callers serialise. A brand-new tenant starts at 1001, matching the previous
-- behaviour (the old code seeded max=1000 and returned max+1).
create or replace function public.next_order_number(p_restaurant_id uuid)
returns bigint
language sql
security definer
set search_path = public, pg_temp
as $$
  insert into public.order_number_counters as c (restaurant_id, next_number)
  values (p_restaurant_id, 1001)
  on conflict (restaurant_id) do update
    set next_number = c.next_number + 1,
        updated_at  = now()
  returning c.next_number;
$$;

revoke all on function public.next_order_number(uuid) from public;
grant execute on function public.next_order_number(uuid) to service_role;

-- The real backstop. Even if a caller invents a number some other way, the
-- database now refuses a duplicate instead of silently accepting it.
create unique index if not exists orders_restaurant_order_number_key
  on public.orders (restaurant_id, order_number)
  where order_number is not null;
